branch-defaults:
  homepage:
    environment: ayush-env-4
    group_suffix: null
global:
  application_name: ayush-cli
  branch: null
  default_ec2_keyname: aws-ayush-me
  default_platform: Node.js
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application

# 01_envar.config
option_settings:
  aws:elasticbeanstalk:application:environment:
    PORT: 8081
    NODE_ENV: production
    DATABASEURL: mongodb://localhost/ayush
    AWS_SECRET_ACCESS: Wb8GBuctIRo7jEKM8cUOvqD/LKCYfeo95/REsEC+
    AWS_ACCESS_KEY: AKIAICYRTLST3SH6NKPQ
    ADMIN_CODE: jfgurwe@WEQW352
    EMAIL_PWD: gsK@proj3ct23
    COOKIE_SECRET: SDFvfdgufdgkf5346534
    SESSION_ID: rwueryuwFHDFER3784237846DSFCJKDHjkhdsufye723434782493glfgkdsvxcvstrrtui
    
# 02_nodecommand.config
option_settings:
  aws:elasticbeanstalk:container:nodejs:
    NodeCommand: "npm run start"
    NodeVersion: 8.8.1